### ISSUE TITLE
Tomcat-Juli Jar Causes java.lang.NoClassDefFoundError: Could not initialize class org.postgresql.Driver

### ISSUE THREAD

**Issue by munifrog** [caf-archive/opensuse-tomcat-image#41]
If I place `tomcat/lib/postgresql-42.2.19-.jar` (or 42.2.6) and add a resource within `tomcat/conf/server.xml` that defines the connection to a PostgreSQL database, specifically with "initialSize" set, as follows:
```
    <GlobalNamingResources>
        <Resource auth="Container"
                  driverClassName="org.postgresql.Driver"
                  factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory"
                  initialSize="10"
                  name="shared/jdbc/OpsDS"
                  password="password"
                  type="javax.sql.DataSource"
                  url="jdbc:postgresql://myserver:5432/mydatabase"
                  username="mydbuser" />
    </GlobalNamingResources>
```
... and start Tomcat with these commands
``` 
      cd $CATALINA_HOME
      exec /usr/local/bin/gosu ${USER_NON_ROOT}:${USER_NON_ROOT} catalina.sh run
```
... then the CAFapi provided `tomcat/bin/tomcat-juli.jar` interferes with the Tomcat startup, resulting in this error:
```
[02:05:37.109Z #879.001 ERROR -            -   ] o.a.catalina.startup.Catalina: {
"message":"The required Server component failed to start so Tomcat is unable to start.",
"exception":"java.lang.NoClassDefFoundError: Could not initialize class org.postgresql.Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tomcat.dbcp.dbcp2.DriverFactory.createDriver(DriverFactory.java:44)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:462)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:528)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getLogWriter(BasicDataSource.java:1048)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.createDataSource(BasicDataSourceFactory.java:568)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance(BasicDataSourceFactory.java:240)
	at com.netiq.tomcat.jdbc.pool.CustomBasicDataSourceFactory.getObjectInstance(CustomBasicDataSourceFactory.java:78)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:96)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:857)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:160)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:843)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:160)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:843)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:174)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1017)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:557)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:253)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:922)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 7 common frames omitted
```
Using the Java option `-verbose:class` (within the `tomcat/bin/catalina.sh` for the "run" command,) one can see that the `org.postgresql.Driver` class is indeed loaded, just not found at runtime, for some reason.

I can, of course, replace the `tomcat/bin/tomcat-juli.jar` with the official version, but logging then stops showing on the console. I see your `tomcat-juli.jar` `pom.xml` retrieves several packages into it, and I'll guess I'll want them for other reasons too. So, it would be nice if this worked on your end.

**Comment by dermot-hardy** [comment]
[SCMOD-13334](https://portal.digitalsafe.net/browse/SCMOD-13334) raised in Jira so that this issue can be taken into a sprint.

**Comment by munifrog** [comment]
Upon using `caf-logging-tomcat-juli/pom.xml` to build `tomcat-juli.jar` locally, it appears that the filter that includes various files from `tomcat-juli` only needs to restore `OneLineFormatter`  in order to resolve this issue.

I tried to submit a pull request, but it would not go through. This is what that section would look like:
```
                                <filter>
                                    <artifact>org.apache.tomcat:tomcat-juli</artifact>
                                    <includes>
                                        <include>org/apache/juli/ClassLoaderLogManager**</include>
                                        <include>org/apache/juli/FileHandler**</include>
                                        <include>org/apache/juli/AsyncFile**</include>
                                        <include>org/apache/juli/OneLineFormatter**</include>
                                        <include>org/apache/juli/WebappProperties.class</include>
                                        <include>META-INF/LICENSE</include>
                                        <include>META-INF/NOTICE</include>
                                    </includes>
                                </filter>
```

**Comment by munifrog** [comment]
Thanks for adding me.

I eventually got my credentials in order and was able to submit [this PR](https://github.com/CAFapi/opensuse-tomcat-image/pull/42).

**Comment by DavidGerald-Milligan** [comment]
I have tested and merged this PR https://portal.digitalsafe.net/browse/SCMOD-13334

**Comment by dermot-hardy** [comment]
In case you're not aware you can get the pre-release image from the `prereleases` repository:

    docker image pull cafapi/prereleases:opensuse-tomcat-5.4.0-SNAPSHOT

Let us know if you need the 5.4.0 image released.
